name: Delete S3 Bucket

on:
  workflow_dispatch:  # Manually trigger from GitHub UI

jobs:
  delete-s3:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1   # or your preferred region

    - name: Empty the S3 bucket
      run: |
        aws s3 rm s3://your-bucket-name --recursive || true

    - name: Delete the S3 bucket
      run: |
        aws s3api delete-bucket --bucket your-bucket-name --region us-east-1
